### ISSUE TITLE
coach运行连接问题

### ISSUE THREAD

**Issue by HubFire** [nubot-nudt/coach4sim#1]
[ERROR] [1487604602.711823467, 1117.655000000]: Client [/gazebo] wants topic /nubot/receive_from_coach to have datatype/md5sum [nubot_common/CoachInfo/1d1d66a902b8fe8ac284f51c0af16e45], but our version has [nubot_common/CoachInfo/7bb01a0f4328cb28beb61d4f502c2969]. Dropping connection.

**Comment by nubot-nudt** [comment]
Please make sure you are using the right packages. Please refer to https://github.com/nubot-nudt/gazebo_visual for how to use gazebo_visual, coach4sim and nubot_ws together.

**Comment by HubFire** [comment]
I have read the document, gazebo_visual, coach4sim and nubot_ws can also run together, but the coach4sim command line reported a connection error.

**Comment by nubot-nudt** [comment]
Are Coachinfo.msg in gazebo_visual and coach4sim the same? I have tested them and they work very well.

**Comment by HubFire** [comment]
When I run the gazebo_visual code directly, the problem is solved, and the gazebo_visual in the running simatch

**Comment by nubot-nudt** [comment]
Please note that gazebo_visual, coach4sim and nubot_ws should be used together; their messages definitions are different from those in simatch (a separated self-contained repository). Please DO NOT crossly use them unless you know how to modify those messages.

**Comment by HubFire** [comment]
thanks  very much
